---
abstract: 'Perl interface to the PLplot plotting library'
author:
  - 'Tim Jenness <t.jenness@jach.hawaii.edu>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  Alien::PLplot: '0'
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Graphics-PLplot
no_index:
  directory:
    - t
    - inc
requires:
  Alien::PLplot: '0'
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
